################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8p1 \
ra/fsp/src/r_gpt \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sci_b_uart \
ra/lvgl/lvgl/demos/benchmark/assets \
ra/lvgl/lvgl/demos/benchmark \
ra/lvgl/lvgl/demos/keypad_encoder \
ra/lvgl/lvgl/demos \
ra/lvgl/lvgl/demos/music/assets \
ra/lvgl/lvgl/demos/music \
ra/lvgl/lvgl/demos/render/assets \
ra/lvgl/lvgl/demos/render \
ra/lvgl/lvgl/demos/stress \
ra/lvgl/lvgl/demos/vector_graphic/assets \
ra/lvgl/lvgl/demos/vector_graphic \
ra/lvgl/lvgl/demos/widgets/assets \
ra/lvgl/lvgl/demos/widgets \
ra/lvgl/lvgl/examples/anim \
ra/lvgl/lvgl/examples/assets \
ra/lvgl/lvgl/examples/assets/emoji \
ra/lvgl/lvgl/examples/event \
ra/lvgl/lvgl/examples/get_started \
ra/lvgl/lvgl/examples/grad \
ra/lvgl/lvgl/examples/layouts/flex \
ra/lvgl/lvgl/examples/layouts/grid \
ra/lvgl/lvgl/examples/others/file_explorer \
ra/lvgl/lvgl/examples/others/font_manager \
ra/lvgl/lvgl/examples/others/fragment \
ra/lvgl/lvgl/examples/others/gestures \
ra/lvgl/lvgl/examples/others/gridnav \
ra/lvgl/lvgl/examples/others/ime \
ra/lvgl/lvgl/examples/others/imgfont \
ra/lvgl/lvgl/examples/others/monkey \
ra/lvgl/lvgl/examples/others/observer \
ra/lvgl/lvgl/examples/others/snapshot \
ra/lvgl/lvgl/examples/others/xml \
ra/lvgl/lvgl/examples/porting \
ra/lvgl/lvgl/examples/porting/osal \
ra/lvgl/lvgl/examples/scroll \
ra/lvgl/lvgl/examples/styles \
ra/lvgl/lvgl/examples/widgets/animimg \
ra/lvgl/lvgl/examples/widgets/arc \
ra/lvgl/lvgl/examples/widgets/bar \
ra/lvgl/lvgl/examples/widgets/button \
ra/lvgl/lvgl/examples/widgets/buttonmatrix \
ra/lvgl/lvgl/examples/widgets/calendar \
ra/lvgl/lvgl/examples/widgets/canvas \
ra/lvgl/lvgl/examples/widgets/chart \
ra/lvgl/lvgl/examples/widgets/checkbox \
ra/lvgl/lvgl/examples/widgets/dropdown \
ra/lvgl/lvgl/examples/widgets/image \
ra/lvgl/lvgl/examples/widgets/imagebutton \
ra/lvgl/lvgl/examples/widgets/keyboard \
ra/lvgl/lvgl/examples/widgets/label \
ra/lvgl/lvgl/examples/widgets/led \
ra/lvgl/lvgl/examples/widgets/line \
ra/lvgl/lvgl/examples/widgets/list \
ra/lvgl/lvgl/examples/widgets/lottie \
ra/lvgl/lvgl/examples/widgets/menu \
ra/lvgl/lvgl/examples/widgets/msgbox \
ra/lvgl/lvgl/examples/widgets/obj \
ra/lvgl/lvgl/examples/widgets/roller \
ra/lvgl/lvgl/examples/widgets/scale \
ra/lvgl/lvgl/examples/widgets/slider \
ra/lvgl/lvgl/examples/widgets/span \
ra/lvgl/lvgl/examples/widgets/spinbox \
ra/lvgl/lvgl/examples/widgets/spinner \
ra/lvgl/lvgl/examples/widgets/switch \
ra/lvgl/lvgl/examples/widgets/table \
ra/lvgl/lvgl/examples/widgets/tabview \
ra/lvgl/lvgl/examples/widgets/textarea \
ra/lvgl/lvgl/examples/widgets/tileview \
ra/lvgl/lvgl/examples/widgets/win \
ra/lvgl/lvgl/src/core \
ra/lvgl/lvgl/src/display \
ra/lvgl/lvgl/src/draw \
ra/lvgl/lvgl/src/draw/renesas/dave2d \
ra/lvgl/lvgl/src/draw/sw/blend \
ra/lvgl/lvgl/src/draw/sw \
ra/lvgl/lvgl/src/font \
ra/lvgl/lvgl/src/indev \
ra/lvgl/lvgl/src/layouts/flex \
ra/lvgl/lvgl/src/layouts/grid \
ra/lvgl/lvgl/src/layouts \
ra/lvgl/lvgl/src/libs/barcode \
ra/lvgl/lvgl/src/libs/bin_decoder \
ra/lvgl/lvgl/src/libs/bmp \
ra/lvgl/lvgl/src/libs/expat \
ra/lvgl/lvgl/src/libs/fsdrv \
ra/lvgl/lvgl/src/libs/lodepng \
ra/lvgl/lvgl/src/libs/lz4 \
ra/lvgl/lvgl/src/libs/qrcode \
ra/lvgl/lvgl/src/libs/rle \
ra/lvgl/lvgl/src/libs/svg \
ra/lvgl/lvgl/src/libs/tiny_ttf \
ra/lvgl/lvgl/src \
ra/lvgl/lvgl/src/misc/cache/class \
ra/lvgl/lvgl/src/misc/cache/instance \
ra/lvgl/lvgl/src/misc/cache \
ra/lvgl/lvgl/src/misc \
ra/lvgl/lvgl/src/osal \
ra/lvgl/lvgl/src/others/file_explorer \
ra/lvgl/lvgl/src/others/font_manager \
ra/lvgl/lvgl/src/others/fragment \
ra/lvgl/lvgl/src/others/gridnav \
ra/lvgl/lvgl/src/others/ime \
ra/lvgl/lvgl/src/others/imgfont \
ra/lvgl/lvgl/src/others/monkey \
ra/lvgl/lvgl/src/others/observer \
ra/lvgl/lvgl/src/others/snapshot \
ra/lvgl/lvgl/src/others/sysmon \
ra/lvgl/lvgl/src/others/test \
ra/lvgl/lvgl/src/others/xml \
ra/lvgl/lvgl/src/others/xml/parsers \
ra/lvgl/lvgl/src/stdlib/builtin \
ra/lvgl/lvgl/src/stdlib/clib \
ra/lvgl/lvgl/src/stdlib \
ra/lvgl/lvgl/src/stdlib/uefi \
ra/lvgl/lvgl/src/themes/default \
ra/lvgl/lvgl/src/themes \
ra/lvgl/lvgl/src/themes/mono \
ra/lvgl/lvgl/src/themes/simple \
ra/lvgl/lvgl/src/tick \
ra/lvgl/lvgl/src/widgets/3dtexture \
ra/lvgl/lvgl/src/widgets/animimage \
ra/lvgl/lvgl/src/widgets/arc \
ra/lvgl/lvgl/src/widgets/bar \
ra/lvgl/lvgl/src/widgets/button \
ra/lvgl/lvgl/src/widgets/buttonmatrix \
ra/lvgl/lvgl/src/widgets/calendar \
ra/lvgl/lvgl/src/widgets/canvas \
ra/lvgl/lvgl/src/widgets/chart \
ra/lvgl/lvgl/src/widgets/checkbox \
ra/lvgl/lvgl/src/widgets/dropdown \
ra/lvgl/lvgl/src/widgets/image \
ra/lvgl/lvgl/src/widgets/imagebutton \
ra/lvgl/lvgl/src/widgets/keyboard \
ra/lvgl/lvgl/src/widgets/label \
ra/lvgl/lvgl/src/widgets/led \
ra/lvgl/lvgl/src/widgets/line \
ra/lvgl/lvgl/src/widgets/list \
ra/lvgl/lvgl/src/widgets/lottie \
ra/lvgl/lvgl/src/widgets/menu \
ra/lvgl/lvgl/src/widgets/msgbox \
ra/lvgl/lvgl/src/widgets/objx_templ \
ra/lvgl/lvgl/src/widgets/property \
ra/lvgl/lvgl/src/widgets/roller \
ra/lvgl/lvgl/src/widgets/scale \
ra/lvgl/lvgl/src/widgets/slider \
ra/lvgl/lvgl/src/widgets/span \
ra/lvgl/lvgl/src/widgets/spinbox \
ra/lvgl/lvgl/src/widgets/spinner \
ra/lvgl/lvgl/src/widgets/switch \
ra/lvgl/lvgl/src/widgets/table \
ra/lvgl/lvgl/src/widgets/tabview \
ra/lvgl/lvgl/src/widgets/textarea \
ra/lvgl/lvgl/src/widgets/tileview \
ra/lvgl/lvgl/src/widgets/win \
ra_gen \
src \
src/segger_rtt \

